<?php 
# Code generated by sdkgen
# Generated on 2020-07-28 16:24:19.4049006 +0000 UTC using container gcr.io/repcore-prod/sdkgen:latest
# DO NOT EDIT!
namespace Vendasta\Godaddy\V1\internal;

use Vendasta\Godaddy\V1\Config;

class GoDaddyGeneratedClient
{
    private $transport;
    
    /**
     * GoDaddyGeneratedClient constructor.
     * @param string $env one of \Vendasta\Vax\Environment::<Env>
     * @param float $default_timeout
     */
    public function __construct(string $env, float $default_timeout = 10000)
    {
        $this->transport = $this->getTransportClient($env, $default_timeout);
    }

    /**
     * @param string $env one of \Vendasta\Vax\Environment::<Env>
     * @param float $default_timeout
     * @return GoDaddyClientInterface
     */
    private function getTransportClient(string $env, float $default_timeout = 10000): GoDaddyClientInterface
    {
        $config = $this->getEnvConfig($env);

        if (class_exists('Grpc\ChannelCredentials', true)) {
            return new GoDaddyGRPCClient(
                $config['host'],
                $config['scope'],
                $config['secure'],
                $default_timeout
            );
        } else {
            return new GoDaddyHTTPClient(
                $config['host'],
                $config['scope'],
                $config['secure'],
                $default_timeout
            );
        }
    }

    /**
     * @param string $env one of \Vendasta\Vax\Environment::<Env>
     * @return array
     */
    private function getEnvConfig(string $env): array {
        return Config::ENVIRONMENT_PARAMS[$env];
    }
    
    /**
     * @param \Godaddy\V1\GetDomainSuggestionAndPriceRequest $req proto request message
     * @param array $options optional options, possible keys:
     *              \Vendasta\Vax\RequestOptions::*
     * @return \Godaddy\V1\GetDomainSuggestionAndPriceResponse proto response message
     * @throws \Vendasta\Vax\SDKException if this call encounters an error
     */
    public function GetDomainSuggestionAndPrice(\Godaddy\V1\GetDomainSuggestionAndPriceRequest $req, array $options = []): \Godaddy\V1\GetDomainSuggestionAndPriceResponse
    {
        return $this->transport->GetDomainSuggestionAndPrice($req, $options);
    }
    
    /**
     * @param \Godaddy\V1\ListDNSRecordsRequest $req proto request message
     * @param array $options optional options, possible keys:
     *              \Vendasta\Vax\RequestOptions::*
     * @return \Godaddy\V1\ListDNSRecordsResponse proto response message
     * @throws \Vendasta\Vax\SDKException if this call encounters an error
     */
    public function ListDNSRecords(\Godaddy\V1\ListDNSRecordsRequest $req, array $options = []): \Godaddy\V1\ListDNSRecordsResponse
    {
        return $this->transport->ListDNSRecords($req, $options);
    }
    
    /**
     * @param \Godaddy\V1\PutDNSRecordRequest $req proto request message
     * @param array $options optional options, possible keys:
     *              \Vendasta\Vax\RequestOptions::*
     * @return \Google\Protobuf\GPBEmpty proto response message
     * @throws \Vendasta\Vax\SDKException if this call encounters an error
     */
    public function PutDNSRecord(\Godaddy\V1\PutDNSRecordRequest $req, array $options = []): \Google\Protobuf\GPBEmpty
    {
        return $this->transport->PutDNSRecord($req, $options);
    }
    
    /**
     * @param \Godaddy\V1\ReplaceDNSRecordsForTypeRequest $req proto request message
     * @param array $options optional options, possible keys:
     *              \Vendasta\Vax\RequestOptions::*
     * @return \Google\Protobuf\GPBEmpty proto response message
     * @throws \Vendasta\Vax\SDKException if this call encounters an error
     */
    public function ReplaceDNSRecordsForType(\Godaddy\V1\ReplaceDNSRecordsForTypeRequest $req, array $options = []): \Google\Protobuf\GPBEmpty
    {
        return $this->transport->ReplaceDNSRecordsForType($req, $options);
    }
    
    /**
     * @param \Godaddy\V1\ReplaceAllDNSRecordsRequest $req proto request message
     * @param array $options optional options, possible keys:
     *              \Vendasta\Vax\RequestOptions::*
     * @return \Google\Protobuf\GPBEmpty proto response message
     * @throws \Vendasta\Vax\SDKException if this call encounters an error
     */
    public function ReplaceAllDNSRecords(\Godaddy\V1\ReplaceAllDNSRecordsRequest $req, array $options = []): \Google\Protobuf\GPBEmpty
    {
        return $this->transport->ReplaceAllDNSRecords($req, $options);
    }
    
    /**
     * @param \Godaddy\V1\DeleteDNSRecordRequest $req proto request message
     * @param array $options optional options, possible keys:
     *              \Vendasta\Vax\RequestOptions::*
     * @return \Google\Protobuf\GPBEmpty proto response message
     * @throws \Vendasta\Vax\SDKException if this call encounters an error
     */
    public function DeleteDNSRecord(\Godaddy\V1\DeleteDNSRecordRequest $req, array $options = []): \Google\Protobuf\GPBEmpty
    {
        return $this->transport->DeleteDNSRecord($req, $options);
    }
    
    /**
     * @param \Godaddy\V1\GetDomainAvailableRequest $req proto request message
     * @param array $options optional options, possible keys:
     *              \Vendasta\Vax\RequestOptions::*
     * @return \Godaddy\V1\GetDomainAvailableResponse proto response message
     * @throws \Vendasta\Vax\SDKException if this call encounters an error
     */
    public function GetDomainAvailable(\Godaddy\V1\GetDomainAvailableRequest $req, array $options = []): \Godaddy\V1\GetDomainAvailableResponse
    {
        return $this->transport->GetDomainAvailable($req, $options);
    }
    
    /**
     * @param \Godaddy\V1\GetDomainAgreementsRequest $req proto request message
     * @param array $options optional options, possible keys:
     *              \Vendasta\Vax\RequestOptions::*
     * @return \Godaddy\V1\GetDomainAgreementsResponse proto response message
     * @throws \Vendasta\Vax\SDKException if this call encounters an error
     */
    public function GetDomainAgreements(\Godaddy\V1\GetDomainAgreementsRequest $req, array $options = []): \Godaddy\V1\GetDomainAgreementsResponse
    {
        return $this->transport->GetDomainAgreements($req, $options);
    }
    
    /**
     * @param \Godaddy\V1\ValidateDomainContactRequest $req proto request message
     * @param array $options optional options, possible keys:
     *              \Vendasta\Vax\RequestOptions::*
     * @return \Godaddy\V1\ValidateDomainContactResponse proto response message
     * @throws \Vendasta\Vax\SDKException if this call encounters an error
     */
    public function ValidateDomainContact(\Godaddy\V1\ValidateDomainContactRequest $req, array $options = []): \Godaddy\V1\ValidateDomainContactResponse
    {
        return $this->transport->ValidateDomainContact($req, $options);
    }
    
    /**
     * @param \Godaddy\V1\ListDomainsByBusinessIDRequest $req proto request message
     * @param array $options optional options, possible keys:
     *              \Vendasta\Vax\RequestOptions::*
     * @return \Godaddy\V1\ListDomainsByBusinessIDResponse proto response message
     * @throws \Vendasta\Vax\SDKException if this call encounters an error
     */
    public function ListDomainsByBusinessID(\Godaddy\V1\ListDomainsByBusinessIDRequest $req, array $options = []): \Godaddy\V1\ListDomainsByBusinessIDResponse
    {
        return $this->transport->ListDomainsByBusinessID($req, $options);
    }
    
    /**
     * @param \Godaddy\V1\TransferDomainRequest $req proto request message
     * @param array $options optional options, possible keys:
     *              \Vendasta\Vax\RequestOptions::*
     * @return \Google\Protobuf\GPBEmpty proto response message
     * @throws \Vendasta\Vax\SDKException if this call encounters an error
     */
    public function TransferDomain(\Godaddy\V1\TransferDomainRequest $req, array $options = []): \Google\Protobuf\GPBEmpty
    {
        return $this->transport->TransferDomain($req, $options);
    }
    
}
